[package]
name = "checksitemap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.18.3"
quick-xml = "0.38.4"
rayon = "1.11.0"
reqwest = { version = "0.11", features = ["blocking"] }
